version: '2.1'
services:
  wave-mongo:
    container_name: wave-mongo
    image: mongo
    restart: always
    healthcheck:
      test: mongo --eval 'db.getCollectionNames()'
      interval: 10s
      timeout: 2s
      retries: 10
    volumes:
      - wave-mongodb-vol:/data/db
    ports:
      - 127.0.0.1:$PAC_MONGO_EXTERNAL_PORT:27017
    networks:
      - services-tier

  wave-node:
    container_name: wave-node
    restart: always
    depends_on:
      wave-mongo:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - services-tier
    ports:
      - $JRS_CONNECTOR_HOST:$JRS_CONNECTOR_PORT:$JRS_CONNECTOR_PORT
      - $JRS_METRICS_HOST:$JRS_METRICS_PORT:$JRS_METRICS_PORT
    env_file:
      - .env

volumes:
  wave-mongodb-vol:

networks:
  services-tier:

